# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sckuykendall.github.io/nb_blog/"

git_url = "https://github.com/sckuykendall/nb_blog/tree/master/"

def custom_doc_links(name): return None
